### ISSUE TITLE
Please add formatting based on template

### ISSUE THREAD

**Issue by DRVTiny** [lbarasti/diagnostic-logger#1]
Your logger seems to be most user friednly logger for crystal: it tries to do formatting that looks good, it knows about multithreading possibilities of modern Crystal.
It will be very helpful if you can add user formatting like in Log4j but simpler (maybe not so "clever" and complex). 
For example
"%d | %L | %P.%F | %m"
To output
date-with-time | ERROR | ProcessID.FiberObjectID | message

Thank you for your work! I hope this shard will mutate to something like log4crystal sometime :)

**Comment by lbarasti** [comment]
@DRVTiny thanks!
I am totally with you, I'd like to keep it simple and provide basic formatting options that can be set via the config. I'm working on some performance improvements ATM, but will then look into formatting :+1: 
BTW, PRs are welcome, even if just to start a conversation on how to do something, so if you have an idea, I'd love to see what it could look like in code.

**Comment by lbarasti** [comment]
I added support for basic template-based formatting, so you can now specify a `pattern` in your appender.
```
logger:
  level: INFO
  appender:
    name: FILE
    class: FileAppender # | ConsoleAppender
    file: app.log
    # pattern supports the following keys: date, level, pid, logger, fiber, msg
    pattern: "[%{date}] [%{level}] [%{logger}] [%{fiber}] - %{msg}"
```

See [this commit](https://github.com/lbarasti/diagnostic-logger/commit/21ff544cb6597e3ff0138b075887c77f570fc8d7) for more details.

Nowhere near complete, but should do for now?
